import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import { Archivo } from "next/font/google";

import localFont from "next/font/local";
import "./globals.css";

const archivo = Archivo({
  weight: ["100", "800"],
  subsets: ["latin"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/d6f07bc8a3.js"
          crossOrigin="anonymous"
          async
        ></script>
      </head>
      <body className={` ${archivo.className} antialiased `}>
        <div>
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
