import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import { Archivo } from "next/font/google";

import "./globals.css";

const archivo = Archivo({
  weight: ["100", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PassionGeek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/d6f07bc8a3.js"
          crossOrigin="anonymous"
          async
        ></script>
      </head>
      <body className={` ${archivo.className} antialiased `}>
        <div className="sticky top-0 z-50">
          <Navbar />
        </div>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
